- src/lib/components/ManagePanel.js
Code stolen from TabCenter.  😉
Looks like this:
I left the `www.` in because it doesn't take up that much room, and it's kinda nice to know the actual host…
Fixes #28.
> Only show the hostname if we're using http(s).

- .eslintrc.json
- src/background.js
- src/popup/snooze-content.js
- Switch to a single alarm to wake up and check for (over)due tabs,
rather than setting an alarm for each tab
- Set wake-up alarm on init
- More logging chatter when NODE_ENV === 'development'
- Misc reorg & tidying to make init flow clearer
Fixes #33
> refactor: Use a single wake-up alarm for all tabs

- bin/build-addon.sh
- circle.yml
- package.json
* `circle.yml` to run linting, tests, and build script on commits
* `bin/build-addon.sh` for Test Pilot deployment automation
* Added an `id` to `package.json` per Test Pilot deploy docs
* Remove packaging from `npm run build` script
* `npm test` now runs linting and outputs a TBD for tests
Fixes #53.
Fixes #57.
> chore: Set up linting, tests, & deployment for CI

- src/lib/components/ManagePanel.js
* Handle times of 'next' by putting them at the front, in title order.
* Show the year for things that aren't this year, to make it more obvious.
Fixes #84.
> fix: Sort snoozed tabs by snooze date.

- src/lib/components/ManagePanel.js
- src/popup/snooze.scss
Also don't animate in the manage panel if it's the first one.
Fixes #83.
Fixes #87.
> fix: Use the full height of the popup for managing tabs.

- src/background.js
- src/lib/components/MainPanel.js
- src/lib/times.js
- src/popup/snooze-content.js
* Simplify the logic because we know we only have one tab to close.
* Move the 'pick' constant into `times.js`
* Donʼt show the 'pick' option in the context menu.
* Don't show the context menu in private windows.
Fixes #88.
Fixes #91.
Fixes #96.
> fix: Snooze the correct tab from the context menu.

- package.json
Context menus on tabs are not yet supported in Dev Edition (v52). So,
opening Nightly (v53) works better for trying out cutting-edge APIs?
> chore: Open Nightly instead of Dev Edition for `npm run`

- src/background.js
- src/manifest.json
We can't get an event on uninstall, so let's just always keep them around.
They _should_ be in the same order as in the Manage panel.
Fixes #42.
> fix: Sync snoozed tabs to a bookmark folder.

- src/lib/components/MainPanel.js
- Hover styles still active, but click handlers disabled when panel is
obscured and inactive.
Fixed #138.
> fix: Disable options & footer buttons in main panel when inactive

- package.json
- src/manifest.json
Forgot to do this before production push, so this is kind of a retro-port of the version bump I did there.
> chore: bump version to 1.0.11

- src/lib/confirm-bar.js
- CSS tweaks in snooze notification bar to override specific styles
applying to the injected notification bar on instagram.com and
washingtonpost.com
Fixes #153.
Fixes #157.
> fix: CSS tweaks for notification bar on Instagram & WaPo

- README.md
- bin/build-addon.sh
- rollup.config.js
- src/background.js
- src/lib/metrics.js
- src/lib/times.js
- src/lib/utils.js
- src/popup/snooze-content.js
- Only include "Real Soon Now" snooze time when `NODE_ENV===development`
- Use real `NODE_ENV` in `rollup.config.js` setup of `replace()` plugin,
with a default of `development` when not set
- Move to inline conditionals using `process.env.NODE_ENV` because
rollup will omit code blocks from bundles where that resolves to false
- Build both development & production artifacts in CircleCI
- README updates
Fixes #155.
> refactor: Build changes for NODE_ENV={development,production}

- package.json
- src/manifest.json
Kind of a proactive version bump, here. We should probably do this after every production deploy, so the next one goes smoothly.
> chore: Bump to v1.0.12

- locales/en-US/snoozetabs.properties
- locales/it/snoozetabs.properties
- pontoon-to-webext.js
- src/lib/components/ManagePanel.js
- src/lib/times.js
I kept separate commits on purpose.
Commit 1:
* Rename timeNextOpenLong to timeUpcomingNextOpen. As it is, it's completely unclear where it's used (I assumed as a tooltip somewhere)
* Change placeholder in confirmTimeTitle to make it clear it’s not an actual time
* Reorganize strings more logically
* Improve localization comments
Commit 2:
Split a string in two just to display it on two lines is quite awful, and will probably lead to poor translations if localizers don't test. I'm pretty sure those 4 lines of JS are cringeworthy, but at least you avoid injecting raw HTML in the first span.
Commit 3:
Italian localization, since I've updated the original file (currently in the l10n branch) to test. You will have to ignore the one in the branch when merging.
> Improve localization

- package.json
Had created the initial GA property as a "web site".  Created a new one that's a "mobile app" and this ID switches us over to that.
> fix: Move GA tracking to a mobile app property

- src/background.js
- Switch from `schedule` to `confirm` message handler in `update`
Fixes #158.
> fix: Correctly re-schedule snoozed tab

- src/background.js
- src/lib/times.js
- src/popup/snooze-content.js
- test/.setup.js
Because we're part of the browser, not part of the page.
(Also it makes the code shorter.  😉)
Fixes #185.
> fix: Use UILanguage instead of AcceptLanguages.

- package.json
Another reason for #110 and consistency - add-on ID was correct in `manifest.json` but not `package.json`
> fix: correct add-on ID in package.json

- src/lib/time-formats.js
- src/lib/times.js
Add some unfortunately-less-localizable date formats, and use those instead.
(I rather liked the IIFE to populate the formats based on which language you were using at install-time. 😉)
Fixes #172.
> fix: Correctly localize dates and times.

- package.json
- src/manifest.json
Just released v1.0.14, so we're working toward 1.0.15 now
> chore: Pre-bump version to 1.0.15

- src/lib/metrics.js
- test/lib/metrics-test.js
Still kind of stumbling toward understanding GA, and it seems like the integer `snooze_time` should be handled as a metric to measure and not a dimension by which to group measurements.
> fix: snooze_time should be a GA metric, not dimension

- locales/en-US/snoozetabs.properties
- locales/it/snoozetabs.properties
- src/background.js
- src/lib/components/DatePickerPanel.js
- src/lib/components/ManagePanel.js
- src/lib/time-formats.js
- src/lib/times.js
- src/popup/snooze-content.js
- test/.setup.js
Also remove moment-locales to save space.
Fixes #204.
> fix: Use Intl for formatting dates and times.

- src/lib/components/DatePickerPanel.js
- src/lib/time-formats.js
This is embarrassing, I've used MM (month) instead of mm (minutes) in the format.
This also moves the logic to time-formats.js
> Fix minutes display in timepicker

- src/lib/components/ManagePanel.js
- src/popup/snooze.scss
It was getting the wrong size from the "don't show the confirmation" checkbox div.
Fixes #195.
> fix: Fix font size of the confirm button in the Date Picker.

- src/background.js
Turns out we never did have a `link.png`.  Huh.  🙂
Tested on Windows only.
Fixes #226.
> fix: Use the application's icon for the notification.

- README.md
- package.json
Two things:
1. Removed the `run` task from `npm start` because a) it doesn't work on Windows and b) I've been finding it way more useful to just have a spare browser profile rather than starting from a blank new one every time.
1. Storybook is broken right now (#177) and it doesn't seem to work on Windows either right now, so let's drop it until at least the former is fixed.
> refactor: Stop running `run` and `storybook` tasks in `start`

- src/lib/components/SnoozePopup.js
- src/popup/snooze-content.js
- Let React handle state for the root component, rather than
re-rendering manually from snooze-content.js
- Stop resetting activePanel to main or manage on every storage change
Issue #124.
Issue #114.
> refactor: Better state management in root popup component

- src/lib/utils.js
Turns out logging would be super handy to have enabled in production builds as users report issues and look in the console for more information.
> fix: Enable logging on production builds

- package.json
- src/lib/components/MainPanel.js
- src/lib/components/ManagePanel.js
- src/lib/components/SnoozePopup.js
- src/popup/snooze.scss
- Remove resize event hook for swapping styles
- Remove .popup-narrow styles
- Styling tweaks to make the normal wide panel styles scroll in the menu
- Only render panel components when active, because their presence
"off-stage" screws up X scrolling in the menu
Fixes #179.
> refactor: Stop attempting to switch styles based on document width

- .sass-lint.yml
- src/lib/components/MainPanel.js
- src/lib/components/ManagePanel.js
- src/popup/snooze-bootstrap.js
- src/popup/snooze-content.js
- src/popup/snooze.scss
- Move resize width detection into bootstrap script to catch event as
early as possible
- Only watch for the first resize event, stop listening after (to address [this issue reported on Discourse](https://discourse.mozilla-community.org/t/snooze-tabs-pane-flickers-on-opening/13872))
- More logging from bootstrap script
- Re-add styles removed for #179
- Tweak styles to better use flexbox and absolute sizing on toolbar
Fixes #263.
> Re-introduce toolbar vs menu styling

- bin/build-locales.js
- package.json
- New `config.productionLocales` property in `package.json` to
select locales for production build
- `bin/build-locales.js` helper script to select locales for
`pontoon-to-webext`
- `cross-spawn` dependency to try to make this work on Windows
Fixes #275.
> fix: Only build manually selected locales for production

- src/background.js
Seems nicer than just deleting it.  We may end up with a lot of Snoozed
Tabs backup folders, but that's probably better than the alternative.
Fixes #237.
> fix: Rename previous Snoozed Tabs bookmarks folder on install.

- .storybook/config.js
- package.json
- src/lib/components/SnoozePopup.js
- src/popup/snooze.scss
- stories/index.js
- Stripped down SnoozePopup component in stories, since that component
now does a lot of app logic and state management
- Narrow styles less specific to make stories easier to mock
- Mocks for global browser.i18n APIs in `.storybook/config.js`
- Upgrade `@kadira/storybook` dependency
- Typo fix in SnoozePopup component, drop unused `narrowPopup` state
Fixes #177.
> fix: Get React Storybook working again

- locales/en-US/snoozetabs.properties
- src/background.js
To prevent sync fights.
Fixes #273.
Again, sorta.
> fix: Add a unique string to the bookmark folder.

- src/background.js
Fixes #272.
Not sure why this was `<= 1` rather than just `< 1`, but it seems to fix this particular bug. Wondering if I'm missing an edge case here though.
> fix: Only open a new tab if there are none left after snoozing

- src/background.js
- src/popup/snooze-content.js
Also log (but otherwise ignore) errors creating tabs (so that we can continue to awaken further tabs, and so that we don't loop continually trying to re-wake the same invalid tab).
Fixes #266.
> fix: Don't snooze `file://` tabs.

- src/background.js
- src/lib/storage.js
`Next Open` now opens on the active non-private-browsing window in the next session (or the first non-private-browsing window if the active window is private, or the window it was snoozed from if that window isn't private)…
It's a little complicated to describe, but I think it's doing the right thing in all the cases I could think of…
Fixes #287.
> fix: Don't wake tabs up in incognito windows.

- src/background.js
- src/lib/storage.js
- Rather than watch for window creation events, just abort waking any
new tabs and reschedule until there's a public window available
- Misc refactorings & cleanups to untangle the code a bit
Fixes #294.
Fixes #295.
Fixes #296.
This might be a little drastic. But, stumbling through trying to diagnose / fix this, I took a step back in commits and tried coming at it from another angle. Also refactored some hunks into functions so I could see some things more clearly.
Behavior in this PR is that the add-on will just skip opening tabs due to wake until there's a non-incognito window available. Downside is that it will repeatedly check every 5 seconds if there are only incognito windows open, but upside is that it ensures the timer gets set on startup. Seemed like we were missing a window …
> Rework handling of incognito windows & waking tabs

- .sass-lint.yml
- package.json
- src/lib/components/SnoozePopup.js
- src/lib/utils.js
- src/popup/snooze.scss
- stories/index.js
- Apply dir="{ltr,rtl}" as appropriate to root component in popup
- Add rtl-detect dependency to identify RTL locales
- Style tweaks to properly lay out time options for RTL
- Panel slides in from left for RTL locale
- Tweak SASS lint nesting-depth to work with RTL exceptions
- Fixes for a few propTypes warnings in storybook
Fixes #281.
> Tweaks to accomodate RTL languages

- locales/en-US/snoozetabs.properties
- package.json
- src/lib/components/DatePickerPanel.js
- src/lib/time-formats.js
- stories/index.js
- Patch Moment.format() to use Intl.DateTimeFormat() API for rc-calendar
locale formatters in DatePickerPanel
- Upgrade rc-calendar component to 8.1.0
- Import additional locales supplied by new version of rc-calendar
- Drop rc-calendar strings that don't seem reachable from our use case
of the component
- Add more detailed comments before each of the remaining new strings
- Small bugfix for storybook
- Small bugfix for initially null datetime on "Pick" time option (#304)
Fixes #305.
Fixes #304.
> Improve l10n on DatePickerPanel component

- src/popup/snooze.scss
> Add horizontal padding to prevent checkbox label being cut off in menu

- bin/build-addon.sh
- circle.yml
- package.json
- `npm run package` now produces `addon.xpi` per new Mozilla Extension
signing conventions
- Update `bin/build-addon.sh` to expect `addon.xpi` on dev builds
- Leave the signing code alone in `bin/build-addon.sh`, which *should* continue to work for "legacy" signing against AMO
- `circle.yml` moves `*.xpi` rather than `*.zip` into artifacts
> fix: Rework add-on build & packaging for new Mozilla Extension signing

- src/lib/confirm-bar.js
Looks like scoped CSS is not working as expected, so let's brute-force
this to select just for the confirm bar CSS.
Fixes #340.
> fix: Constrain confirm bar CSS to element ID

- src/lib/confirm-bar.js
Mostly stole the idea for this from [the notification bar in bitwarden](https://github.com/bitwarden/browser/blob/master/src/content/notificationBar.js#L340), but hacked it a bit to preserve our dynamic HTML for l10n. Seems to work and should more effectively isolate styles
Fixes #383.
Fixes #380.
Fixes #371.
Fixes #340.
> fix: Move confirmation bar into an iframe to further isolate styles

- bin/generate-manifest.js
Looks like the ID for the WebExtension in the manifest.json was left
off, which means the extension was getting a generated ID.
That ID didn't end in @mozilla.com, which means that the [context-fill
feature][context-fill] feature wasn't enabled.
This also would have caused other problems.
[context-fill]: https://dxr.mozilla.org/mozilla-central/source/layout/svg/SVGContextPaint.cpp#69
Fixes #401.
> Fix ID in webext manifest

- bin/generate-manifest.js
- package.json
- src/lib/metrics.js
- test/lib/metrics-test.js
- Remove custom Test Pilot update URL in anticipation of moving to AMO
- Drop dependence on the testpilot-metrics package, send metric pings
only to Google Analytics
- Update metrics tests to reflect that Snooze Tabs is handling its own
GA events now.
- Bump add-on minor version to reflect graduation
Issue #421.
> Prep for Test Pilot graduation by dropping update URL and Telemetry
