bwinton/SnoozeTabs

src/popup/snooze-content.js, src/popup/snooze.scss
* Restore React import for popup JS
* Fix positioning of calendar panels
Fixes #52.
=> fix: Repair things broken for bad linting

src/background.js
Just a quick fix, I'm fairly sure we want to re-schedule the next alarm when the current one fires, so I added a call to do that.  (Also I printed out the console message in a friendlier format for ease of debugging/inspecting. 😉)
=> fix: Update the wake alarm after we fire a notification.

src/background.js, src/lib/components/DatePickerPanel.js, src/lib/components/MainPanel.js, src/lib/components/ManagePanel.js, src/popup/snooze.scss
This one's a twofer - #36 for wrapping the Calendar control and then #50 to ensure that calendar will only allow values in the future.
=> Constrain date/time selection to future

src/manifest.json
=> Add author, homepage_url, and icons to manifest.json

src/lib/components/ManagePanel.js
=> Strip any leading www. from displayed domain names

src/background.js, src/icons/Disabled Bell Icon.svg, src/lib/components/ManagePanel.js, src/popup/snooze-content.js, src/popup/snooze.scss
We can only restore certain urls so let's not let people snooze them!
But we don't want to disable the button entirely, so if they click it, just show them the manage panel.
Fixes #59.
=> fix: Disable the snooze button for special urls.

.eslintignore, .eslintrc.json, package.json, rollup.config.js, src/background.js, src/lib/components/DatePickerPanel.js, src/lib/components/ManagePanel.js, stories/index.js
This will also make sure the /stories/* are linted as well as /*.js files.
¯\\\_(ツ)\_/¯
=> Run ESLint against all the JS files

src/lib/components/DatePickerPanel.js, src/popup/snooze.scss
* Darken light fonts to make them easier to read.
* Make header and footer unselectable.
* Add active states for footer buttons.
* Remove seconds from the time picker.
Fixes #66.
Fixes #89.
Fixes #90.
Fixes #92.
=> fix: Random CSS updates and small tweaks.

src/lib/components/MainPanel.js
=> fix: Remove "Snooze Tab until..." row from panel

src/popup/snooze-content.js
=> fix: Display snoozed tab's site favicon.

src/lib/components/DatePickerPanel.js
=> fix: Disable "Snooze" button when selected time passes

.eslintignore, .gitignore, bin/build-addon.sh, package.json, src/manifest.json
* Add data/** to .eslintignore
* Add web-ext-artifacts/ to .gitignore
* Bump addon to v1.0.9 (it took 9 tries to get deployment to work)
* Ensure the correct signed .xpi gets renamed to signed-addon.xpi
Fixes #102.
=> fix: Resolve issues with deployment scripting

bin/build-addon.sh
| &nbsp; | STEP | TIME | CIRCLE BUILD
|----|----|----:|:----:|
| **Before:** | `$ ./bin/build-addon.sh` | 00:53 | [104](https://circleci.com/gh/bwinton/SnoozeTabs/104?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
| **After:** | `$ ./bin/build-addon.sh` | 00:34 | [105](https://circleci.com/gh/bwinton/SnoozeTabs/105?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
Fixes #133
=> Move 'npm run build' into else block

package.json
=> fix: Pin web-ext dependency to known working v1.7.0

src/lib/components/MainPanel.js, src/lib/components/ManagePanel.js
=> fix: Ignore button clicks when panels obscured by date picker

src/background.js
=> fix: Donʼt disable menu items, since theyʼll be hidden when inapplicable.

src/popup/snooze-content.js, src/popup/snooze.scss
=> fix: More narrow panel style tweaks for Windows

package.json
=> Update web-ext package to v1.8.1

src/popup/snooze.scss
=> fix: Add hover color state to delete button on manage panel

README.md
=> fix: Add credits for the icons.

src/manifest.json
=> fix: Set the tooltip on the browser action.

.sass-lint.yml, src/lib/components/MainPanel.js, src/popup/snooze.scss
- Adds `defaultDateChoice` state to MainPanel
- Style & event handler to turn option dates into links
- Link click pre-fills the datetime picker with the clicked value
Fixes #69.
=> feat: Allow users to edit default snooze times

src/popup/snooze.scss
=> fix: Remove the panel shadow when in narrow menu panel

src/popup/snooze.scss
=> fix: Tweak colors in panel footer buttons

package.json, src/manifest.json
Just pushed master to production at v1.0.12. So, this PR gets us ready for the next push
=> Bump to v1.0.13

src/manifest.json
=> fix: Add `update_url` to enable Test Pilot updates.

src/lib/confirm-bar.js
=> fix: Clear text-shadow for confirmation bar text

src/background.js
=> fix: Snooze tab without confirmation when confirm bar injection fails

src/lib/time-formats.js, src/lib/times.js
=> fix: Display year if snooze time is not in current year

src/background.js
=> fix: Do not display confirmation bar for tabs snoozed via tab context menu

src/popup/snooze.scss
- Smaller size is closer to 16px actual size of most favicons
- Added small padding to content area of management entries
Fixes #119.
Fixes #144.
=> fix: Reduce size of favicons in management panel to be less blurry

bin/pontoon-to-webext.js
This came up in a Page Shot review that included a copypasta'd pontoon-to-webext.js. Nice idea, thought it seemed worth upstreaming :+1:
=> Tweak fatal error handling in pontoon-to-webext script

.eslintrc.json, src/lib/components/DatePickerPanel.js, src/lib/components/MainPanel.js, src/lib/components/ManagePanel.js, src/lib/components/SnoozePopup.js
=> chore: Add React PropTypes for more linting goodness.

package.json
Doh!  I totally noticed this in review, but forgot to mention it.  :(
=> fix: Get Windows building again.

package.json
Forgot to do this after the last release!
=> chore: Bump version to v1.0.16

src/lib/confirm-bar.js
=> fix: Reduce margin between checkbox & label in confirmation bar

src/popup/snooze.scss
=> fix: Tweak year size in selection panel in calendar widget

src/background.js, src/popup/snooze-content.js
=> Simplify 'undelete' handling to save alarm without tab manipulation

src/popup/snooze.scss
=> Ensure time option text does not push other elements off the panel

locales/en-US/snoozetabs.properties, src/lib/components/DatePickerPanel.js
=> Enable l10n for the calendar widget

package.json
- See https://pontoon.mozilla.org/projects/test-pilot-snoozetabs/
- See also https://l10n.mozilla-community.org/webstatus/api/?product=testpilot-snoozetabs&txt&type=complete
=> Update productionLocales to reflect current set of 100% locales

src/lib/confirm-bar.js
=> Include language direction on confirmation bar injected into pages

locales/es-ES/snoozetabs.properties, locales/hu/snoozetabs.properties, package.json
Fixes lower-case strings in hu locale, adds the es-ES locale that just got to 100%
=> L10n 1.0.17 2

package.json
Turns out recent changes to two dependencies and fuzzy package.json versions breaks our build.
=> Pin rc-animate and rc-trigger dependencies to fix build

package.json
Bumping version ahead of time so subsequent changes fall into next release
=> chore: Bump to v1.0.21

package.json
I had been running things in WSL bash. Tried switching to PowerShell and saw it was broken. Here's a quick fix.
=> fix: Small fix for an npm script not working in windows powershell

src/lib/time-formats.js
=> fix: Show minutes in short_time

package.json
=> fix: Correct the updateURL

bin/generate-manifest.js, package.json
=> fix: Change name from "snoozetabs" to "Snooze Tabs"

src/popup/snooze.scss
=> fix arrow and height issues on windows

src/lib/confirm-bar.js
One more tweak to better match [Photon design system](https://design.firefox.com/photon/components/buttons.html#default-4)
Issue #415.
=> fix: Further tweak confirm bar buttons to match Photon spec

package-lock.json, src/lib/components/DatePickerPanel.js, src/lib/components/MainPanel.js, src/lib/components/ManagePanel.js, src/lib/confirm-bar.js, src/popup/snooze.scss
This is mildly WIP, but resolves both of the visual glitches as well as most of the A11y issues in the ESR branch. I will file separate (non-blocking) issues for remaining a11y concerns.
=> a11y and glitch fixes

webpack.config.js
This allowed me to compile and run the addon.
=> Modernizer webpack configuration

src/background.js, src/lib/utils.js, src/popup/snooze-content.js
Fixes #424.
@rugk, @gaul: Either of you want to take a look at this and give it a 👍🏼/👎🏼?
=> Handle reader-mode tabs, by storing an extra bit of info in the message.
